/*
==================================================
QRTalk 3.1
Configurações de entrada, segurança e inatividade
==================================================
*/

"use strict";

(() => {
    const minutes = (value) => value * 60 * 1000;

    window.QRTalkSafetyConfig = {
        admission: {
            requestTimeoutMs: minutes(2)
        },

        inactivity: {
            timeoutMs: minutes(10),
            warningBeforeMs: minutes(1),
            activityBroadcastIntervalMs: 45 * 1000
        },

        policy: {
            maxViolations: 2,

            /*
            Expressões suficientemente específicas para indicar
            paquera, romance ou conversa íntima. Elas são avaliadas
            depois da normalização de acentos, pontuação e algumas
            substituições comuns de caracteres.
            */
            romanticPhrases: [
                "te amo",
                "eu te amo",
                "amo voce",
                "amo vc",
                "estou apaixonado por voce",
                "estou apaixonada por voce",
                "apaixonado por voce",
                "apaixonada por voce",
                "quero ficar com voce",
                "quero ficar com vc",
                "fica comigo",
                "quer ficar comigo",
                "quer namorar comigo",
                "vamos namorar",
                "voce quer namorar",
                "vc quer namorar",
                "meu amor",
                "minha vida",
                "amor da minha vida",
                "meu bem",
                "minha princesa",
                "meu principe",
                "meu bebe",
                "minha bebe",
                "meu nenem",
                "minha nenem",
                "meu lindo",
                "minha linda",
                "lindo demais",
                "linda demais",
                "voce e lindo",
                "voce e linda",
                "vc e lindo",
                "vc e linda",
                "oi lindo",
                "oi linda",
                "ola lindo",
                "ola linda",
                "bom dia amor",
                "boa tarde amor",
                "boa noite amor",
                "dorme bem amor",
                "sonha comigo",
                "sonhei com voce",
                "sonhei com vc",
                "estou com saudade de voce",
                "estou com saudades de voce",
                "to com saudade de voce",
                "to com saudade de vc",
                "sinto sua falta",
                "queria estar com voce",
                "queria estar com vc",
                "quero te ver",
                "quero ver voce",
                "quero ver vc",
                "vamos nos encontrar",
                "vamos sair juntos",
                "vamos sair escondido",
                "vamos sair escondida",
                "vamos conversar escondido",
                "vamos conversar escondida",
                "nao conta para ninguem",
                "nao conte para ninguem",
                "fica entre nos",
                "nosso segredo",
                "conversa em segredo",
                "beijo para voce",
                "beijo pra voce",
                "beijo pra vc",
                "beijo na boca",
                "quero te beijar",
                "queria te beijar",
                "me da um beijo",
                "me manda beijo",
                "manda beijo",
                "beijos gostosos",
                "voce mexe comigo",
                "vc mexe comigo",
                "nao paro de pensar em voce",
                "nao paro de pensar em vc",
                "penso em voce toda hora",
                "penso em vc toda hora",
                "voce e especial para mim",
                "vc e especial para mim",
                "gosto muito de voce",
                "gosto muito de vc",
                "estou gostando de voce",
                "estou gostando de vc",
                "quero voce comigo",
                "quero vc comigo",
                "queria voce aqui",
                "queria vc aqui",
                "me chama de amor",
                "meu coracao e seu",
                "meu coracao e teu",
                "casa comigo",
                "quer casar comigo",
                "voce e minha",
                "voce e meu",
                "vc e minha",
                "vc e meu"
            ],

            /*
            Termos de carinho muito associados a conversa afetiva.
            Os termos ambíguos são combinados com pronomes, saudações
            ou mais de um sinal antes de gerar bloqueio.
            */
            affectionTerms: [
                "amorzinho",
                "amorzão",
                "amorzao",
                "mozão",
                "mozao",
                "mozinho",
                "mozinha",
                "benzinho",
                "xuxu",
                "chuchu",
                "gatinha",
                "gatinho",
                "gata",
                "gato",
                "princesa",
                "principe",
                "lindinha",
                "lindinho",
                "fofinha",
                "fofinho",
                "delicia",
                "gostosa",
                "gostoso",
                "paixao",
                "apaixonado",
                "apaixonada",
                "namoradinha",
                "namoradinho",
                "namorada",
                "namorado",
                "crush",
                "vida",
                "bebe",
                "nenem",
                "querida",
                "querido",
                "linda",
                "lindo",
                "amor"
            ],

            directAddressTerms: [
                "voce",
                "vc",
                "tu",
                "te",
                "teu",
                "tua",
                "meu",
                "minha",
                "oi",
                "ola",
                "hey",
                "bom dia",
                "boa tarde",
                "boa noite"
            ],

            /*
            Frases e termos íntimos ou sexualizados. Termos com usos
            administrativos legítimos recebem exceções em policy.js.
            */
            intimatePhrases: [
                "manda nude",
                "manda nudes",
                "me manda nude",
                "me manda nudes",
                "manda foto pelada",
                "manda foto pelado",
                "me manda foto pelada",
                "me manda foto pelado",
                "foto sem roupa",
                "manda foto sem roupa",
                "quero ver voce pelada",
                "quero ver voce pelado",
                "quero ver vc pelada",
                "quero ver vc pelado",
                "tira a roupa",
                "fica sem roupa",
                "video pelada",
                "video pelado",
                "chamada picante",
                "conversa picante",
                "mensagem picante",
                "foto intima",
                "fotos intimas",
                "imagem intima",
                "imagens intimas",
                "quero fazer sexo",
                "vamos fazer sexo",
                "fazer amor com voce",
                "dormir com voce",
                "dormir com vc",
                "vem para minha cama",
                "vem pra minha cama",
                "estou com tesao",
                "voce me da tesao",
                "vc me da tesao",
                "voce e gostosa",
                "voce e gostoso",
                "vc e gostosa",
                "vc e gostoso",
                "que corpo gostoso",
                "que corpo gostosa",
                "quero seu corpo",
                "manda uma foto sua gostosa",
                "manda uma foto sua gostoso",
                "safada gostosa",
                "safado gostoso",
                "quero te pegar",
                "vou te pegar",
                "quero te tocar",
                "quero te sentir",
                "beijar seu corpo",
                "sexo escondido",
                "encontro escondido",
                "trair comigo",
                "vamos trair",
                "nao fala para seu marido",
                "nao fala pro seu marido",
                "nao fala para sua esposa",
                "nao fala pra sua esposa",
                "seu marido nao precisa saber",
                "sua esposa nao precisa saber"
            ],

            intimateTerms: [
                "nude",
                "nudes",
                "pelada",
                "pelado",
                "seminua",
                "seminu",
                "tesao",
                "excitado",
                "excitada",
                "orgasmo",
                "masturbacao",
                "masturbar",
                "transar",
                "transa",
                "sexo",
                "sexual",
                "sensual",
                "erotico",
                "erotica",
                "safada",
                "safado"
            ],

            /*
            Combinações de alto risco. A lista não tenta determinar
            idade ou identidade: apenas bloqueia frases explícitas.
            */
            highRiskPhrases: [
                "nao conta para seus pais",
                "nao conte para seus pais",
                "nao conta pra sua mae",
                "nao conta pro seu pai",
                "apaga nossa conversa",
                "apague nossa conversa",
                "manda foto e nao conta",
                "manda nude e nao conta",
                "isso fica entre nos dois",
                "ninguem pode saber da gente",
                "qual sua idade manda foto",
                "quantos anos voce tem manda foto",
                "quantos anos vc tem manda foto"
            ]
        }
    };
})();
